name: Distribute app to Play Store

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Version of application (e.g. v1.0.0)'
        required: true
        default: v1.0.0
      branch:
        description: 'From which branch the application will be built'
        required: true
        default: main

jobs:
  build:
    uses: pezkuwichain/pezkuwi-wallet-android/.github/workflows/android_build.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      gradlew-command: bundleReleaseMarket
      keystore-file-name: market_key.jks
    secrets: inherit

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-bundle
          path: app/bundle

      - name: Download mapping artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-mapping
          path: app/mapping
        continue-on-error: true

      - name: Rename artifacts
        run: mv app/bundle/releaseMarket/app-releaseMarket.aab app/bundle/releaseMarket/pezkuwi-wallet-android-${{ github.event.inputs.app_version }}.aab

      - name: Market publication
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          packageName: io.pezkuwichain.wallet
          releaseFiles: app/bundle/releaseMarket/pezkuwi-wallet-android-${{ github.event.inputs.app_version }}.aab
          track: alpha
          status: draft
          inAppUpdatePriority: 2
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/mapping/releaseMarket/mapping.txt
