name: Build and deploy release apk

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: pezkuwichain/pezkuwi-wallet-android/.github/workflows/android_build.yml@main
    with:
      branch: main
      gradlew-command: assembleReleaseMarket
      keystore-file-name: market_key.jks
    secrets: inherit

  upload-to-firebase:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: app

      - name: üó≥ Upload to Firebase
        uses: ./.github/workflows/upload-to-firebase
        with:
          appId: ${{ secrets.ANDROID_RELEASE_FIREBASE_APP_ID }}
          firebase-token: ${{ secrets.RELEASE_FIREBASE_CREDENTIAL }}
          releaseNotes: ${{ github.event.head_commit.message }}
          test-groups: dev-team
          upload-file: app/releaseMarket/app-releaseMarket.apk

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      s3_url: ${{ steps.s3_upload.outputs.s3_url }}
    env:
      S3_BUCKET: s3://pezkuwi-wallet-android-app
      S3_REGION: nl-ams

    steps:
      - uses: actions/checkout@v4
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: app

      - name: ‚öôÔ∏è Upload to S3
        id: s3_upload
        uses: ./.github/workflows/upload-to-s3
        with:
          s3_region: ${{ env.S3_REGION }}
          s3_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          s3_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          s3_bucket: ${{ env.S3_BUCKET }}
          upload_file: app/releaseMarket/app-releaseMarket.apk

      - name: Show S3 URL
        run: |
          echo "App uploaded to: ${{ steps.s3_upload.outputs.s3_url }}"

  appium-mobile-tests:
    needs: [upload-to-s3]
    if: ${{ always() && needs.upload-to-s3.result == 'success' }}
    uses: ./.github/workflows/appium-mobile-tests.yml
    with:
      app_url: ${{ needs.upload-to-s3.outputs.s3_url }}
      test_grep: "android"
      allure_job_run_id: ""
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.PAT_TOKEN }}
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
